### ISSUE TITLE
Do away with, or better define, "Figure x" convention

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/OWASP-Testing-Guide-v5#158]
**Describe the issue**

By the convention of numbering figures, any time an image is added to a section that does not come at the end of the existing text, every figure that succeeds the new image must have its caption renamed. This is already the case, as an image that was added in section 2 doesn't yet have a "Figure x" caption. To add one and keep up the convention, we'd have to change the captions of all remaining figures in the book.

This convention is already broken in some sections; 4.2.1 uses "Figure 4.2.1-x", yet in 4.2.3 there is a "Figure 10."

I propose either doing away with the "Figure x" convention altogether, and descriptively captioning images without them; or standardizing the section-specific "Figure x.x.x-x" convention, which is more easily maintained.

**Comment by kingthorin** [comment]
Ya there was a long discussion about this on slack. 

Chances are 4.2.3 hasn't been updated since the decision was made.

Per the slack chat we agreed to sequential numbering within section/sub-section to minimize what would require re-numbering.
