### ISSUE TITLE
Testing phases in introductory sections are confusing

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/OWASP-Testing-Guide-v5#161]
# Issue

In section 3, the OWASP Testing _Framework_ is described as some different activities that occur at specific phases of software creation:

> - Before development begins
> - During definition and design
> - During development
> - During deployment
> - Maintenance and operations

In section 4.1, the Testing _Methodology_ is described as a model with three components:

> - Tester: Who performs the testing activities
> - Tools and methodology: The core of this Testing Guide project
> - Application: The black box to test

As well as a "test divided into 2 phases: Phase 1 Passive Mode... Phase 2 Active Mode."

The division of Phase 1 and 2 is contradicted by the appearance of "Information Gathering" in both.

The issues that occur to me are as follows:

- [ ] The use of the term "phases" in both sections is confusing. The list of phases of the Testing Framework makes sense, and I think it should be retained here, since it describes the process of the SDLC. I think the "phases" of the Testing Methodology don't make sense, primarily due to the "information gathering" contradiction. If there is indeed a real separation in the Methodology, I think it should be worded differently and I'm open to suggestions.

- [ ] It is unclear where the Testing Methodology fits into the Testing Framework. I would suggest "Phase 4: During Deployment" but this is not explicitly stated. Additionally, Testing Methodology can be used separately from the Testing Framework (e.g., testing someone else's project as a researcher) and this too should be stated.

# Proposed solution

Rewrite "4.1 What is the OWASP Testing Methodology" to do away with the separate phases, and instead simply introduce the components and the 11 categories of testing covered later in 4.

**Comment by ThunderSon** [comment]
For the confusion concern, it is clearly stated `phases of software creation`. It does not relate to 4.1 technically. It's mainly where security should be integrated.
As for the second point, I see some validity. I will review it further and see what we can propose. Would love to chat more on both as well. Not in a blocking mode on the first point at all 😄 We can have chats on Slack and then discuss bigger points over here.
