### ISSUE TITLE
Update 4.2.2 Fingerprint Web Server

### ISSUE THREAD

**Issue by victoriadrake** [OWASP/OWASP-Testing-Guide-v5#169]
This section seems long out of date and I'd like to take a crack at making it useful again. Here's how I'd restructure it and what I think should be covered.

I would appreciate some input from the community - your preferred tools, personal experiences, and any tips or links to articles that I may benefit from incorporating into my research. :pray: 

---

# Fingerprint Web Server

## Summary
- Explain how it works and why it's useful

## Test Objectives

"Determine the version and type of a running web server to enable further discovery of any known vulnerabilities."

### Manual methods

- Banner grabbing
- Sending malformed requests
- ~~Cookie inspection (sounds yummier than it is)~~ No recent relevant info I could find

### Automated tools

- A menu of well-maintained tools for fingerprinting, how and why they work differently

## Remediation

- Briefly explain strategies for combating web server fingerprinting
- Reverse proxy server protection
- Mention keeping server up to date and patched

**Comment by citybasebrooks** [comment]
Nikto and nmap are lightweight tools useful for fingerprinting web servers.  

Virtually all dynamic testing tools (DAST) will include one or more tests designed to identify a web server/application version.  While there are ways to do this type of work manually most of the manual inspection of cookies, headers, resquest/response behavior, etc. has been automated.
