### ISSUE TITLE
Is this project going ahead?

### ISSUE THREAD

**Issue by anantshri** [OWASP/OWASP-Testing-Guide-v5#18]
Multiple questions:
I don't see any activities whole of 2018. Is this project still in progress?
Any place we can keep a track on roadmap?
I am interested in contributing to various sections, just a standard pull request or do you want anything else there is no guideline referenced anywhere?

**Comment by kingthorin** [comment]
@anantshri I've been in-touch with the project leaders about this. I'm told that they are ready for contributions. So I'd say just go ahead and start submitting PRs.

https://twitter.com/kingthorin_rm/status/1097520686732595201

**Comment by kingthorin** [comment]
Confirming a few PRs of mine and one from another contributor have been merged this week. So bring on the contributions @anantshri and everyone!

**Comment by kingthorin** [comment]
> I am interested in contributing to various sections, just a standard pull request or do you want anything else there is no guideline referenced anywhere?

Yes just a standard PR is great.
