### ISSUE TITLE
Add Testing for Server-Side Request Forgery (SSRF)

### ISSUE THREAD

**Issue by MatOwasp** [OWASP/OWASP-Testing-Guide-v5#3]

**Comment by MatOwasp** [comment]
4aed335fe2d8a65e64539fa9215ebf77976935a1

**Comment by ManhNho** [comment]
[aec0b76](https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/20/commits/aec0b766d74dc320f7d883dd5202f16e21e071e8)

**Comment by kingthorin** [comment]
This issue can be closed, content on this subject has been added.
