### ISSUE TITLE
Add Testing for Sub-domain take over

### ISSUE THREAD

**Issue by ManhNho** [OWASP/OWASP-Testing-Guide-v5#31]
Hi @MatOwasp,

I just read about [NEW TESTS TO WRITE](https://github.com/OWASP/OWASP-Testing-Guide-v5/blob/master/OWASP%20Summit%20Outcome) and [OWASP testing guide v4](https://github.com/OWASP/OWASP-Testing-Guide-v5/blob/master/document/OWASP%20Testing%20Guide%20v4%20Table%20of%20Contents.md). And I did not see any topics about Testing subdomain take over techniques. Can we add a topic about this attacking case?

**Comment by MatOwasp** [comment]
Hi, I add @kingthorin. @ManhNho  what contents would you like to add?
Something like this article? https://www.hackerone.com/blog/Guide-Subdomain-Takeovers

**Comment by ManhNho** [comment]
Yeah, some content about Subdomain takeover techniques. Can I start writing content for this?

**Comment by ManhNho** [comment]
I suggest that we create an article in [Configuration and Deployment Management Testing](https://github.com/OWASP/OWASP-Testing-Guide-v5/tree/master/document/4%20Web%20Application%20Security%20Testing/4.3%20Configuration%20and%20Deployment%20Management%20Testing) that talks about how the guide can be used for Sub-domain takeover testing.

**Comment by kingthorin** [comment]
Seems fine to me.

**Comment by MatOwasp** [comment]
ok thanks

**Comment by jzold** [comment]
Hi,

I'm happy to help with this one, just uploaded a draft version to https://github.com/jzold/OWASP-Testing-Guide-v5/blob/master/document/4%20Web%20Application%20Security%20Testing/4.3%20Configuration%20and%20Deployment%20Management%20Testing/4.3.10%20Test%20for%20subdomain%20takeover%20(OTG-CONFIG-010).md

Any feedback is welcome and appreciated :) I'll submit a PR shortly.

J./

**Comment by kingthorin** [comment]
Closed in https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/58
