### ISSUE TITLE
Review/Fix "Testing for API.md"

### ISSUE THREAD

**Issue by kingthorin** [OWASP/OWASP-Testing-Guide-v5#35]
OWASP/OWASP-Testing-Guide-v5#33 was merged without review and contains numerous errors or items which should be fixed/tweaked. Including (but not necessarily limited to):
- Typos: `Sate` vs. `State` when elaborating on the acronym REST. `moethods` vs `methods`, `reponses` vs `responses`, etc.
- Sentence fragments:
  - > Web application APIs following the REST style that called REST API.
  - > REST APIs using URIs (Uniform Resource Identifires) to access resources.
  - >  HTTP headers are used in request and reponses. 
  - etc
- Formatting
- Title caps
- Reference consistency (86 or 96?) 
  > RFC3886 URI - https://tools.ietf.org/html/rfc3986

**Comment by ManhNho** [comment]
Thank for your review! Will fix later

**Comment by kingthorin** [comment]
No worries. This isn't a complete review by any means. Just wanted to ensure that the need for review/edits was tracked. (Hence the ticket.)

**Comment by ManhNho** [comment]
hi @kingthorin 
Because of my heavy workload at company, can you help me fix/edit them?

**Comment by ThunderSon** [comment]
Please assign me to this issue. I'll handle it in the coming week/weekend.

**Comment by kingthorin** [comment]
Consider it yours. I'm not able to assign it to you. Probably because of permissions/collaborators, etc. I think we can trust that people will read the issue history before tackling something..... (Otherwise they'll learn a hard lesson I guess :grin: )

**Comment by ManhNho** [comment]
> Please assign me to this issue. I'll handle it in the coming week/weekend.

you are welcome :dango:

**Comment by ManhNho** [comment]
@ThunderSon I just remind you about this case

**Comment by ThunderSon** [comment]
I did not forget about it. I got side-tracked and I have been busy so far.

**Comment by kingthorin** [comment]
Closed with https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/76
