### ISSUE TITLE
Add description, topics for Project (Github Repo)

### ISSUE THREAD

**Issue by ManhNho** [OWASP/OWASP-Testing-Guide-v5#40]
No description, website, or topics provided. I think we need them.

**Comment by kingthorin** [comment]
Ya that seems like a good idea.

![image](https://user-images.githubusercontent.com/7570458/55407237-a1eb0700-552b-11e9-9a9e-ec3a0f8260d7.png)

https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github

**Comment by ManhNho** [comment]
@MatOwasp

**Comment by MatOwasp** [comment]
Sure, good idea, thanks

**Comment by kingthorin** [comment]
@MatOwasp you should be able to use these controls to set the details:
![image](https://user-images.githubusercontent.com/7570458/56683272-29471880-669b-11e9-9ec8-9ab0c39817d2.png)

I don't have access to them in the OTG repo. (The screenshot is based on my access to the zap repo.)

**Comment by ThunderSon** [comment]
@kingthorin Please validate the update 😄

**Comment by ThunderSon** [comment]
@MatOwasp Hi Mat! Kindly note that we are not able to `Manage Topics` despite it being mentioned in the roles of a Maintainer. I sent an email to Github to advise on the issue. Till then, can you update the topics when possible with the following topics?
`owasp` `owasp-top-10` `security` `appsec` `security-testing` `pentesting` `web-security`

**Comment by kingthorin** [comment]
> @kingthorin Please validate the update 😄 

Description looks good to me 👍

**Comment by kingthorin** [comment]
I was finally able to add topics this morning. Closing this ticket.
