### ISSUE TITLE
Lacking Issues and PRs templates

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/OWASP-Testing-Guide-v5#51]
I have found that the repository is lacking issues and PR templates in order to make things smoother for contributors, and for reviewers to better understand the work at hand.

**Comment by kingthorin** [comment]
Ref: https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by ThunderSon** [comment]
@kingthorin this can be closed, right? Or you think that we need to anything further? I set in the PR template a box to say that the issue has been fully covered, in a way to say go ahead and close it :)

**Comment by kingthorin** [comment]
The one template still needs the label element set. I can do that if you want.

On that commit/PR a keyword can be used to close this. https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by ThunderSon** [comment]
We'll need to make it a conditional, and what if the PR does not properly close the issue?

**Comment by kingthorin** [comment]
Labels can always be changed after the fact, plus the user can tweak it at creation. To me it's more often applicable than not.

As for closing keywords, I meant specifically you could use that for this one. Not that it shoukd be part of the template. For other instances, if a user incorrectly closes with a keyword that should be caught during PR review and if missed then the issue can be manually re-opened.

**Comment by ThunderSon** [comment]
For the label we're at an agreement. As for the closing, alrightie.
