### ISSUE TITLE
Add 4.8.19 Server-Side Template Injection SSTI (OTG-INPVAL-019)

### ISSUE THREAD

**Issue by jzold** [OWASP/OWASP-Testing-Guide-v5#64]
New content proposed for the input validation section of OWASP

Please let me know your thoughts

Thanks
J./

**Comment by ManhNho** [comment]
I will handle this test case next week

**Comment by jzold** [comment]
Thanks @ManhNho :)

**Comment by jzold** [comment]
hi @ManhNho 
any progress on this one?

Thanks
J./

**Comment by ThunderSon** [comment]
@jzold what proposed content is being discussed in this issue? Or are you talking in general? The issue feels like it could have a better description.

**Comment by jzold** [comment]
@ThunderSon this is new content proposed to the OWASP document - I think the description is clear enough: 'Add 4.8.19 Server-Side Template Injection SSTI (OTG-INPVAL-019)'

any other questions please let me know

J./

**Comment by ThunderSon** [comment]
Oh! Forgive me, I thought you were amending an existing section. Do you have any references that you'll be following? I can say it'd be safe for you to tackle it if you feel like you have the time for it, as I don't see any PR or extra document in @ManhNho 's fork.

**Comment by jzold** [comment]
the action is with @ManhNho at this stage let's wait his feedback for now - just because there is nothing in his fork he might still be working on the draft somewhere outside of GitHub.

@ManhNho  please confirm

Thanks
J./
