### ISSUE TITLE
Change the Naming Convention

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/OWASP-Testing-Guide-v5#65]
**Is your feature request related to a problem? Please describe.**
The file names contain spaces and are not suitable for proper linking in the documents.

**Describe the solution you'd like**
Create a general rule and refactor the files to a certain naming convention

**Comment by ThunderSon** [comment]
@kingthorin this was accomplished by yourself, right?

**Comment by kingthorin** [comment]
Yup, done. I guess #96 duplicated this, oops.
