### ISSUE TITLE
Section 4.2.6 CAT, TamperFox links outdated

### ISSUE THREAD

**Issue by patrickceg** [OWASP/OWASP-Testing-Guide-v5#67]
**Describe the issue**
The (external) links to the tools CAT and TamperFox on the page https://github.com/OWASP/OWASP-Testing-Guide-v5/blob/master/document/4%20Web%20Application%20Security%20Testing/4.2%20Information%20Gathering/4.2.6%20Identify%20application%20entry%20points%20%28OTG-INFO-006%29.md are outdated and currently generate 404 error on the external sites they point to.

Specifically, at the bottom of the page: 
"Intercepting Proxy:\"
- CAT
"Browser Plug-in:\"
- Tamper Data for Firefox - 

**Suggestions and Observations:**
I think Tamper Data died off when Mozilla changed the plugin (e.g. the Kali Linux courses point to outdated versions of Firefox+the plugin). There is a similar plugin https://github.com/Pamblam/Tamper-Data-for-FF-Quantum / https://addons.mozilla.org/en-US/firefox/addon/tamper-data-for-ff-quantum/ 

There is a Tamper for Chrome https://github.com/google/tamperchrome , but I haven't tried it. 

I couldn't find out what happened to the "CAT" tool, nor have I used to to be able to offer ideas of replacements or what it may have been renamed / spun off to.

**Comment by ThunderSon** [comment]
Hello. I as well don't remember ever using CAT.
WebScarab is long gone as well. It has been integrated in ZAP.
Tamper Data's reviews are not anywhere near nice. I'd recommend its complete removal from the guide.
One addition that could be done is fiddler. It could be used as a lightweight proxy that developers are well accustomed with.
Could it be possible that you:
- fix the markdown trailing backslashes? `\`
- Fix the RFC reference to have a proper markdown URL?

**Comment by patrickceg** [comment]
Hmm I looked up "fiddler" and it's also proxy based. Should we just remove the subsections "Intercepting Proxy" and "Browser-Plug-In" such that it just shows ZAP, Burp Suite, and Fiddler?

The browser plugin I've used for proxy based debugging is FoxyProxy (pointed to the ZAP port)... mainly because it came installed by default on the Penetrating with Kali VM I started to learn pentesting on :)

**Comment by ThunderSon** [comment]
Foxy proxy is a great extension.
What you are saying is valid. Please create a PR in order to move forward with this 😄

**Comment by patrickceg** [comment]
Anyway, unless there's a better way I'll just dump it in this comment I'm working on it :) https://github.com/patrickceg/OWASP-Testing-Guide-v5/tree/feature/outdated-links-4.2.6-issue-67

...yuk I don't like putting links manually like this, being used to Atlassian's system where I can click "Create branch" directly from the issue and all the stuff (branch linked to issue, issue linked to branch, task records that I am working on it) happens. At least a quick search doesn't show anything convenient https://stackoverflow.com/questions/41614421/create-new-branch-from-the-issue

**Comment by kingthorin** [comment]
For future reference: https://help.github.com/en/articles/closing-issues-using-keywords
