### ISSUE TITLE
Merge strategy "Squash and merge" at project level

### ISSUE THREAD

**Issue by patrickceg** [OWASP/OWASP-Testing-Guide-v5#68]
**Is your feature request related to a problem? Please describe.**
There was a comment made on pull request #57 about merge strategy being "squash" we should allow the tooling (Github) handle that so we don't need waste time on comments like that.

The comment - https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/57#issuecomment-504703447

**Describe the solution you'd like**
Set the project to enforce merge strategy upon merge of pull requests

**Comment by caperutxa** [comment]
I do not like squash strategy for merges.

Squash remove the commit history in benefit to merge in order to obtain a single view to a group of commits but there are ways to see all changes in a group of commits, between tags... and the history commits is not lost

**Comment by kingthorin** [comment]
IMHO the user's feature branch (for lack of a better term) commit history is irrelevant to the overall project. But that's just my 2 cents.

**Comment by kingthorin** [comment]
Refs: 
- https://help.github.com/en/articles/about-merge-methods-on-github
- https://help.github.com/en/articles/configuring-pull-request-merges

**Comment by ThunderSon** [comment]
I'd mainly recommend the usage of squash strategy when a lot of bad commits have been committed to a PR. Otherwise, the commits are needed to re-track the changes if need be, instead of having it all in one commit.

**Comment by ThunderSon** [comment]
@kingthorin Moving forward, let's set it to Squash and Merge, and when need be, the reviewer can manually take in all commits. Sounds good?

**Comment by kingthorin** [comment]
Seems fine to me, but I don’t think it’s something I can set.

As things are people can use the drop down on the merge button. (It seems to stick with whichever method  was most recently used, until changed again.)

**Comment by patrickceg** [comment]
Should we close this issue? We've been through a whole month of awesome contributions and I don't think this was ever a problem.
