### ISSUE TITLE
Fixed broken links for section 4 content pages

### ISSUE THREAD

**Issue by GT-ACC-RT** [OWASP/OWASP-Testing-Guide-v5#70]
Restored broken links in the content page markdown files under each of the testing categories in section 4.

**Comment by kingthorin** [comment]
Duplicate of https://github.com/OWASP/OWASP-Testing-Guide-v5/issues/10

**Comment by kingthorin** [comment]
Closed in: https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/71
