### ISSUE TITLE
Missing Contribution Guide

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/OWASP-Testing-Guide-v5#73]
**Is your feature request related to a problem? Please describe.**
Contributors don't have any proper guidance, how to present their work, nor what are the best practices for their PRs

**Describe the solution you'd like**
Add a CONTRIBUTING.md specifying how to contribute, how to setup their environment, expected results, etc.

**Comment by patrickceg** [comment]
Another item for the contribution guide is that we should remove (Dead?) Google Group from Readme.md. It seems discussions are occurring on the OWASP Public Slack instead.

**Comment by ThunderSon** [comment]
@patrickceg Hmmm, I think it's alright keeping it. If someone wants something, they can choose between Slack and G Groups. We can simply hint that we are more active on Slack than on the Groups.
