### ISSUE TITLE
CI Checks and Linter Addition

### ISSUE THREAD

**Issue by ThunderSon** [OWASP/OWASP-Testing-Guide-v5#75]
**Is your feature request related to a problem? Please describe.**
The project lacks PR checks where there are no requirements and no baseline checks for accepting them, which could lead to unintentional merges.

**Describe the solution you'd like**
Setup a CI tool (Travis, Circle) based on what works best with the project, ensuring the availability of a linter on top of it to ensure that the best practices are being followed.

**Comment by rejahrehim** [comment]
We could use Travis for basic linting in .md files as we do for SecureTea project and its docs.

**Comment by ThunderSon** [comment]
Exactly the objective! I'll be looking at different Travis implementations for md files and do it. Might you have the time for it? Otherwise, I'd love to set you as a reviewer once I do it 😄

**Comment by rejahrehim** [comment]
One simple option would be configuring Codacy(https://app.codacy.com) which will check for remark-lint (remark-lint is a markdown code style linter. Ensuring the markdown is of great quality to makes sure less refactoring is needed afterwards.

I can do both options.

**Comment by ThunderSon** [comment]
I believe using travis and implementing the markdown linter would be the best choice as this is what I'll be recommending in the environment setup, so that they are in sync. What do you think?

**Comment by rejahrehim** [comment]
Travis will be best if we are planning to use linting in environment setup too. I will send the PR with the first implementation of Travis config.

**Comment by ThunderSon** [comment]
You can check out the new PR https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/99
Just finished the contribution guide, which contains the linter plugin 😄 
I will look at your PR once I can, thank you for your support!

**Comment by kingthorin** [comment]
Ref: https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/223
