### ISSUE TITLE
4.10 Testing for weak Cryptography - v4 Migration Cleanup

### ISSUE THREAD

**Issue by kingthorin** [OWASP/OWASP-Testing-Guide-v5#86]
Should be covered by: https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/57

Someone should just do a sanity check.
- [ ] Sanity check

**Comment by ThunderSon** [comment]
I will be tackling this in the coming days.

**Comment by kingthorin** [comment]
Thanks, remember this is intended to be a migration cleanup activity not a content review :wink:
